# Generated by Django 6.0.6 on 2026-07-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_image_blog_read_count_playlist_image_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("blue", "blue"),
                            ("rose", "rose"),
                            ("amber", "amber"),
                            ("purple", "purple"),
                            ("teal", "teal"),
                            ("indigo", "indigo"),
                        ],
                        default="blue",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to="blog.category",
            ),
        ),
    ]
