# Generated by Django 6.0.6 on 2026-07-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_contactentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
