# Generated by Django 6.0.6 on 2026-07-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
