# Generated by Django 6.0.6 on 2026-07-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blog_options_alter_playlist_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="conclusion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="excerpt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="blog",
            name="introduction",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="sections",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="blog",
            name="subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
