# Generated by Django 6.0.6 on 2026-07-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_blog_conclusion_blog_excerpt_blog_featured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="posted_on_linkedin",
            field=models.BooleanField(default=False),
        ),
    ]
