# Generated by Django 6.0.6 on 2026-07-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_blog_posted_on_linkedin"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="linkedin_post_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
