from fastapi import APIRouter, HTTPException, Depends, Request
from typing import List, Optional, Any, Dict, Union
from pydantic import BaseModel, Field
import uuid
from schemas.blogs import Blog, BlogSection, BlogSectionFlowchartStep

router = APIRouter()

# --- Schemas ---

class GenerateBlogRequest(BaseModel):
    message: str
    session_id: Optional[str] = None

class BlogPromptState(BaseModel):
    """Refined representation of a blog generated by the AI for frontend consumption."""
    title: str
    subtitle: Optional[str] = None
    excerpt: Optional[str] = None
    image: Optional[str] = None
    category: Optional[str] = None
    tags: List[str] = []
    # Nested content structure matches frontend's expectation for the form
    content: Dict[str, Any] 

class GenerateBlogResponse(BaseModel):
    action: str = "generate"
    session_id: str
    conversation: List[Dict[str, str]]
    blog_state: Optional[BlogPromptState] = None

# --- Mock Database / Session Store ---
_sessions = {}

# --- Helper: Generate Mock Content ---
def generate_mock_blog(prompt: str) -> BlogPromptState:
    """Generate a rich, structured blog state using shared schemas."""
    topic = prompt.strip().title()
    
    return BlogPromptState(
        title=f"The Future of {topic}: A 2026 Perspective",
        subtitle=f"How {topic} is evolving in the age of AI and distributed systems.",
        excerpt=f"Discover the core principles and cutting-edge trends that are reshaping {topic} today.",
        image="https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=2072",
        category="Technology",
        tags=[topic.split()[0].lower(), "future", "architecture", "2026"],
        content={
            "introduction": f"In this deep dive, we explore the intricate layers of {topic}. As we head into 2026, the complexity of these systems necessitates a more structured and automated approach.",
            "sections": [
                {
                    "type": "text",
                    "title": f"Why {topic} Matters Now",
                    "content": f"The integration of machine learning and real-time data processing has transformed {topic} from a static field into a dynamic, high-performance ecosystem."
                },
                {
                    "type": "flowchart",
                    "title": f"Standard {topic} Architecture Flow",
                    "steps": [
                        {
                            "id": "step-1",
                            "title": "Data Ingestion",
                            "description": "Raw data enters the system through high-throughput streams.",
                            "color": "blue",
                            "branches": []
                        },
                        {
                            "id": "step-2",
                            "title": "Processing Engine",
                            "description": "Choose the appropriate processing layer based on latency requirements.",
                            "color": "indigo",
                            "branches": [
                                {
                                    "id": "branch-1",
                                    "title": "Batch Processing",
                                    "description": "High throughput, higher latency for historical analysis.",
                                    "color": "violet"
                                },
                                {
                                    "id": "branch-2",
                                    "title": "Stream Processing",
                                    "description": "Real-time, ultra-low latency for instant feedback.",
                                    "color": "purple"
                                }
                            ]
                        },
                        {
                            "id": "step-3",
                            "title": "System Storage",
                            "description": "Final persistent state layer.",
                            "color": "violet",
                            "branches": []
                        }
                    ]
                },
                {
                    "type": "code",
                    "title": "Implementation Snippet",
                    "language": "python",
                    "content": f"def process_{topic.lower().replace(' ', '_')}(data):\n    # Core logic for handling {topic}\n    results = analyze(data)\n    return results"
                }
            ],
            "conclusion": f"Building for the future requires a deep understanding of {topic}. By leveraging modern architectural patterns, we can ensure our systems are both scalable and resilient."
        }
    )

# --- Endpoints ---

@router.post("/generate/", response_model=GenerateBlogResponse)
async def generate_chat(request: GenerateBlogRequest):
    session_id = request.session_id or str(uuid.uuid4())
    
    if session_id not in _sessions:
        _sessions[session_id] = []
    
    # Add user message
    _sessions[session_id].append({"role": "user", "content": request.message})
    
    # Generate Mock Response
    blog_state = generate_mock_blog(request.message)
    assistant_message = f"I've generated a draft for your blog: **{blog_state.title}**. You can see the structure populated in the form below, including a detailed flowchart and code examples."
    
    _sessions[session_id].append({"role": "assistant", "content": assistant_message})
    
    return {
        "session_id": session_id,
        "conversation": _sessions[session_id],
        "blog_state": blog_state
    }

@router.get("/session/{session_id}/")
async def get_session(session_id: str):
    if session_id not in _sessions:
        raise HTTPException(status_code=404, detail="Session not found")
    return {"conversation": _sessions[session_id]}

@router.post("/save/")
async def save_chat_blog(request: Dict[str, str]):
    # In a real app, this would commit the session state to the Blog collection
    return {"message": "Blog generated and ready for final review!"}

@router.delete("/session/{session_id}/")
async def delete_session(session_id: str):
    if session_id in _sessions:
        del _sessions[session_id]
    return {"status": "success"}
