from typing import Dict, Any, Optional
from fastapi import Request
from pydantic import BaseModel
from backbone.generic.views import GenericCustomApi
from backbone.core.permissions import IsOwner, IsAuthenticated
from backbone.schemas import UserOut

class DummySchema(BaseModel):
    pass

class ChatGenerateApi(GenericCustomApi):
    """
    Custom generic API view for generating mock blog data.
    Requires authentication (IsAuthenticated or IsOwner behavior based on Backbone mapping).
    """
    async def post(self, request: Request, data: Dict[str, Any], user: Optional[UserOut]) -> Any:
        # data corresponds to what the frontend sent (e.g., {"message": "...", "session_id": "..."})
        message = data.get("message", "Dummy request")
        
        return {
            "success": True,
            "message": "Successfully mock generated blog",
            "action": "generate",
            "session_id": "test_session_123",
            "conversation": [
                {"role": "user", "content": message},
                {"role": "assistant", "content": f"Successfully generated a mock blog based on: '{message}'. Hello {user.full_name if user else 'Guest'}."}
            ],
            "blog_state": {
                "title": f"A Mock Blog: {message[:15]}...",
                "slug": "mock-generated-blog",
                "subtitle": "Created from a mock API endpoint",
                "excerpt": "This is a short excerpt for the mock generated blog post.",
                "introduction": "Welcome to this mock blog post. This is a dummy introduction generated by our new chat endpoint.",
                "conclusion": "To conclude, this is dummy data loaded automatically.",
                "category": "Technology",
                "tags": ["AI", "Mock", "Test"],
                "image": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
                "featured": False,
                "content": {
                    "introduction": "Welcome to this mock blog post. This is a dummy introduction generated by our new chat endpoint.",
                    "conclusion": "To conclude, this is dummy data loaded automatically.",
                    "sections": [
                        {
                            "type": "text",
                            "title": "Dummy First Section",
                            "content": "This is a generated paragraph of text to demonstrate the functionality."
                        },
                        {
                            "type": "bullets",
                            "title": "Key Points",
                            "items": [
                                "Point one",
                                "Point two",
                                "Point three"
                            ]
                        }
                    ]
                }
            }
        }

# Instantiate the generic router and export it
# Use DummySchema to bypass the repository requirement
# Require auth using `use_auth=True` and `permission_classes=[IsAuthenticated]`
router = ChatGenerateApi(
    schema=DummySchema, 
    prefix="/generate", 
    endpoint="/", 
    tags=["Chats"]
).router
