# Generated by Django 5.1.15 on 2026-02-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="views",
        ),
    ]
