# Generated by Django 6.0 on 2025-12-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_bloglike"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="embedding",
            field=models.JSONField(
                blank=True, help_text="Mistral embeddings (1024 dim)", null=True
            ),
        ),
    ]
