# Generated by Django 5.1.15 on 2026-02-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_blog_embedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
        migrations.RemoveField(
            model_name="bloglike",
            name="blog",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="blogs",
        ),
        migrations.AlterUniqueTogether(
            name="bloglike",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="bloglike",
            name="user",
        ),
        migrations.DeleteModel(
            name="FAQ",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="user",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="BlogLike",
        ),
        migrations.DeleteModel(
            name="Playlist",
        ),
        migrations.DeleteModel(
            name="Testimonial",
        ),
    ]
