[project]
name = "blogermenia-djnago"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.6",
    "django-allauth[socialaccount]>=65.18.0",
    "requests>=2.34.2",
    "pillow>=11.0.0",
    "dicebear-core>=10.3.0",
    "dicebear-styles>=10.2.0",
    "langchain-ollama>=1.1.0",
    "langchain-chroma>=1.1.0",
    "chromadb>=1.5.9",
    "celery[redis]>=5.4.0",
    "redis>=5.2.0",
]
