"""
Django settings for blogermenia project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load the repo-root .env.dev into os.environ (harmless no-op in production —
# docker-compose.prod.yml injects .env.prod straight into the container's
# environment, and load_dotenv() never overrides a variable that's already set).
load_dotenv(BASE_DIR.parent / ".env.dev")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-y-q^vt16l_smw)mq9s0=&@i51+&6$rnxqd4o^@gjv%&i1(*9me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h]

CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o]

# nginx sits in front in production and forwards this header, so Django knows
# the original request was HTTPS even though gunicorn itself only speaks HTTP.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Only enforced once you've actually put TLS in front of nginx — leave off
# (default) while running plain HTTP, or every request loops redirecting.
if not DEBUG and os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "False") == "True":
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "accounts",       # before allauth so our templates/account/ override allauth defaults via APP_DIRS
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "linkedin_oidc",
    "blog",
    "search",
]

# --- Google Gemini (embeddings for semantic search + text generation) ---
GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY", "")
GEMINI_EMBEDDING_MODEL = os.environ.get("GEMINI_EMBEDDING_MODEL", "gemini-embedding-001")
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.5-flash")

# --- Semantic search (Gemini embeddings + ChromaDB vector store) ---
CHROMA_PERSIST_DIR = BASE_DIR / "search" / "chroma_db"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves collected static files directly from gunicorn (compressed +
    # cache-busted) so nginx only has to proxy requests and serve /media/.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "blogermenia.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'blogermenia' / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "blogermenia.context_processors.global_context",
            ],
        },
    },
]

WSGI_APPLICATION = "blogermenia.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# SQLite by default (local dev). Set POSTGRES_DB (docker-compose.prod.yml does)
# to switch to Postgres — no other code changes needed.

if os.environ.get("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["POSTGRES_DB"],
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST", "postgres"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
# `collectstatic` writes here; WhiteNoise serves it straight from gunicorn.
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    # Adds a content hash to each filename + far-future cache headers, and
    # gzip/brotli-compresses everything at collectstatic time.
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# Media files (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.CustomUser"

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = "none"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Email — prints to terminal in dev; switch to SMTP for production
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "Inkwell <noreply@inkwell.dev>"

# --- Production SMTP (uncomment & fill when deploying) ---
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "your@gmail.com"
# EMAIL_HOST_PASSWORD = "your-app-password"

# Bypass the intermediate social login confirmation page (works for GET requests)
SOCIALACCOUNT_LOGIN_ON_GET = True

# Social account provider configuration
SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_PROVIDERS = {
    "linkedin_oauth2": {
        "SCOPE": [
            "openid",
            "profile",
            "email",
            "w_member_social",
        ],
    }
}


# --- Celery (async task queue, backed by Redis) ---
# All CELERY_* settings are picked up by the Celery app in blogermenia/celery.py.
# We use dedicated Redis DBs (2 = broker, 3 = results) so this project never
# shares the default DB 0/1 with any other Celery project on the same machine —
# otherwise workers steal and discard each other's tasks.
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/2")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/3")

# Send/accept only JSON — never pickle (safer, and portable across workers).
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Production-grade reliability & throughput defaults:
# - late ack + reject-on-lost: a task re-runs if a worker dies mid-flight.
# - prefetch 1: fair dispatch for our slow, uneven embedding tasks.
# - result expiry: don't let Redis fill up with old task results.
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 200  # recycle workers to cap memory creep
CELERY_RESULT_EXPIRES = 60 * 60  # seconds
CELERY_TASK_TIME_LIMIT = 300  # hard kill after 5 min
CELERY_TASK_SOFT_TIME_LIMIT = 240  # raise SoftTimeLimitExceeded first
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Periodic jobs (run by `celery beat`). Sweep for any content missing an
# embedding every 6 hours as a safety net behind the real-time signal indexing.
CELERY_BEAT_SCHEDULE = {
    "reindex-missing-embeddings": {
        "task": "search.tasks.reindex_all",
        "schedule": 60 * 60 * 6,  # seconds
        "kwargs": {"only_missing": True},
    },
}
