"""
Django settings for blogermenia project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-y-q^vt16l_smw)mq9s0=&@i51+&6$rnxqd4o^@gjv%&i1(*9me"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "accounts",       # before allauth so our templates/account/ override allauth defaults via APP_DIRS
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "linkedin_oidc",
    "blog",
    "search",
]

# --- Semantic search (Ollama embeddings + ChromaDB vector store) ---
# OLLAMA_BASE_URL is read from the environment so the same code works locally
# (localhost) and inside Docker (host.docker.internal), where Ollama runs on the host.
OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_EMBEDDING_MODEL = os.environ.get("OLLAMA_EMBEDDING_MODEL", "qwen3-embedding:0.6b")
CHROMA_PERSIST_DIR = BASE_DIR / "search" / "chroma_db"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "blogermenia.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'blogermenia' / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "blogermenia.context_processors.global_context",
            ],
        },
    },
]

WSGI_APPLICATION = "blogermenia.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Media files (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.CustomUser"

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = "none"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Email — prints to terminal in dev; switch to SMTP for production
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "Inkwell <noreply@inkwell.dev>"

# --- Production SMTP (uncomment & fill when deploying) ---
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "your@gmail.com"
# EMAIL_HOST_PASSWORD = "your-app-password"

# Bypass the intermediate social login confirmation page (works for GET requests)
SOCIALACCOUNT_LOGIN_ON_GET = True

# Social account provider configuration
SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_PROVIDERS = {
    "linkedin_oauth2": {
        "SCOPE": [
            "openid",
            "profile",
            "email",
            "w_member_social",
        ],
    }
}


# --- Celery (async task queue, backed by Redis) ---
# All CELERY_* settings are picked up by the Celery app in blogermenia/celery.py.
# We use dedicated Redis DBs (2 = broker, 3 = results) so this project never
# shares the default DB 0/1 with any other Celery project on the same machine —
# otherwise workers steal and discard each other's tasks.
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/2")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/3")

# Send/accept only JSON — never pickle (safer, and portable across workers).
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Production-grade reliability & throughput defaults:
# - late ack + reject-on-lost: a task re-runs if a worker dies mid-flight.
# - prefetch 1: fair dispatch for our slow, uneven embedding tasks.
# - result expiry: don't let Redis fill up with old task results.
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 200  # recycle workers to cap memory creep
CELERY_RESULT_EXPIRES = 60 * 60  # seconds
CELERY_TASK_TIME_LIMIT = 300  # hard kill after 5 min
CELERY_TASK_SOFT_TIME_LIMIT = 240  # raise SoftTimeLimitExceeded first
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Periodic jobs (run by `celery beat`). Sweep for any content missing an
# embedding every 6 hours as a safety net behind the real-time signal indexing.
CELERY_BEAT_SCHEDULE = {
    "reindex-missing-embeddings": {
        "task": "search.tasks.reindex_all",
        "schedule": 60 * 60 * 6,  # seconds
        "kwargs": {"only_missing": True},
    },
}
