# Generated by Django 6.0 on 2025-12-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
