# Generated by Django 6.0 on 2025-12-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_remove_blog_tags_delete_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="featured",
        ),
        migrations.AddField(
            model_name="blog",
            name="isPublished",
            field=models.BooleanField(default=False),
        ),
    ]
