"""The post as a downloadable PDF.

One artifact, two consumers: the reader clicking "Download PDF", and the
LinkedIn share, which uploads these same bytes as a document attachment. If
they were generated by two different code paths, the file the author reviews
and the file their network sees could silently diverge — so both call
`blog.services.pdf_service.blog_pdf`, which also means one render serves both.
"""
import json
import logging

from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from drf_spectacular.utils import OpenApiResponse, extend_schema
from rest_framework.exceptions import APIException
from rest_framework.renderers import BaseRenderer, JSONRenderer
from rest_framework.views import APIView

from blog.selectors import visible_blogs
from blog.services.pdf_service import blog_pdf, pdf_filename

logger = logging.getLogger(__name__)


class PdfUnavailable(APIException):
    status_code = 503
    default_detail = "The PDF could not be generated. Please try again shortly."
    default_code = "pdf_unavailable"


class PdfRenderer(BaseRenderer):
    """Declares that this view can answer `Accept: application/pdf`.

    DRF negotiates a renderer in `initial()`, before the handler runs, and the
    project's default is JSON only — so a client asking for a PDF (which is what
    the frontend's binary client asks for) got a 406 before this view was ever
    called. The response body is written by hand below, so this renderer is only
    ever reached for an error body DRF serialises through the negotiated
    renderer.
    """

    media_type = "application/pdf"
    format = "pdf"
    charset = None

    def render(self, data, accepted_media_type=None, renderer_context=None):
        if isinstance(data, bytes):
            return data
        return json.dumps(data, default=str).encode("utf-8")


class BlogPdfView(APIView):
    """`GET /blogs/<slug>/pdf/` — the post as a PDF file."""

    # PDF first, so `Accept: */*` (curl, and every browser's trailing wildcard)
    # resolves to the document. JSON stays available for a client that would
    # rather read the error than the file.
    renderer_classes = [PdfRenderer, JSONRenderer]
    throttle_scope = "read"

    @extend_schema(
        summary="Download a post as a PDF",
        responses={
            200: OpenApiResponse(description="application/pdf"),
            503: OpenApiResponse(description="Rendering failed."),
        },
    )
    def get(self, request, slug):
        # `visible_blogs` is what keeps a draft out of reach of anyone who can
        # guess a slug: the author gets their own drafts, everyone else gets
        # published posts only.
        blog = get_object_or_404(visible_blogs(request), slug=slug)

        try:
            data = blog_pdf(blog)
        except Exception as exc:
            # A 500 here would read as "the site is broken" for what is one
            # unrenderable post. 503 with a message says what actually failed.
            logger.exception("PDF generation failed for blog '%s'", blog.slug)
            raise PdfUnavailable() from exc

        response = HttpResponse(data, content_type="application/pdf")
        # `inline` so the browser's own viewer opens it — the author is meant to
        # see exactly what LinkedIn will get before deciding to share it.
        response["Content-Disposition"] = f'inline; filename="{pdf_filename(blog)}"'
        response["Content-Length"] = str(len(data))
        return response
