from unittest.mock import patch

from django.contrib.auth import get_user_model
from django.test import RequestFactory, TestCase

from .models import Blog, Like, Playlist

User = get_user_model()


class BlogSlugTests(TestCase):
    def setUp(self):
        self.author = User.objects.create_user(username="alice", password="x")

    def test_slug_autogenerated_from_title(self):
        blog = Blog.objects.create(title="Hello World", content="c", author=self.author)
        self.assertEqual(blog.slug, "hello-world")

    def test_duplicate_titles_get_unique_slugs(self):
        b1 = Blog.objects.create(title="Same Title", content="c", author=self.author)
        b2 = Blog.objects.create(title="Same Title", content="c", author=self.author)
        self.assertNotEqual(b1.slug, b2.slug)
        self.assertEqual(b2.slug, "same-title-1")

    def test_editing_keeps_slug_stable(self):
        blog = Blog.objects.create(title="Original", content="c", author=self.author)
        original_slug = blog.slug
        blog.title = "Changed"
        blog.save()
        self.assertEqual(blog.slug, original_slug)


class PlaylistSlugTests(TestCase):
    def test_duplicate_playlist_titles_get_unique_slugs(self):
        author = User.objects.create_user(username="bob", password="x")
        p1 = Playlist.objects.create(title="My List", author=author)
        p2 = Playlist.objects.create(title="My List", author=author)
        self.assertNotEqual(p1.slug, p2.slug)


class ReadCountTests(TestCase):
    def setUp(self):
        self.factory = RequestFactory()
        self.author = User.objects.create_user(username="author", password="x")
        self.reader = User.objects.create_user(username="reader", password="x")
        self.blog = Blog.objects.create(title="Post", content="c", author=self.author)

    def _request(self, user):
        req = self.factory.get("/")
        req.user = user
        return req

    def test_reader_increments_count(self):
        self.blog.register_view(self._request(self.reader))
        self.blog.refresh_from_db()
        self.assertEqual(self.blog.read_count, 1)

    def test_author_own_view_does_not_count(self):
        self.blog.register_view(self._request(self.author))
        self.blog.refresh_from_db()
        self.assertEqual(self.blog.read_count, 0)

    def test_anonymous_view_counts(self):
        # Anonymous readers are the common case for a public blog — they count.
        from django.contrib.auth.models import AnonymousUser
        self.blog.register_view(self._request(AnonymousUser()))
        self.blog.refresh_from_db()
        self.assertEqual(self.blog.read_count, 1)


class LikeTests(TestCase):
    def setUp(self):
        self.author = User.objects.create_user(username="a", password="x")
        self.user = User.objects.create_user(username="u", password="x")
        self.blog = Blog.objects.create(title="P", content="c", author=self.author)

    def test_like_count_and_is_liked_by(self):
        self.assertEqual(self.blog.like_count(), 0)
        self.assertFalse(self.blog.is_liked_by(self.user))
        Like.objects.create(blog=self.blog, user=self.user)
        self.assertEqual(self.blog.like_count(), 1)
        self.assertTrue(self.blog.is_liked_by(self.user))

    def test_like_toggle_view(self):
        self.client.force_login(self.user)
        # First POST likes, second unlikes.
        self.client.post(f"/blogs/{self.blog.slug}/like/")
        self.assertEqual(self.blog.likes.count(), 1)
        self.client.post(f"/blogs/{self.blog.slug}/like/")
        self.assertEqual(self.blog.likes.count(), 0)


class SearchSignalTests(TestCase):
    """Saving content should enqueue a Celery index task (not run inline)."""

    @patch("search.tasks.index_object.delay")
    def test_blog_save_enqueues_index_task(self, mock_delay):
        author = User.objects.create_user(username="c", password="x")
        blog = Blog.objects.create(title="Indexed", content="c", author=author)
        # on_commit callbacks fire at the end of the atomic block; TestCase wraps
        # each test in a transaction, so assert the task was scheduled.
        # (captureOnCommitCallbacks makes the on_commit hooks run.)
        mock_delay.reset_mock()
        with self.captureOnCommitCallbacks(execute=True):
            blog.title = "Indexed again"
            blog.save()
        mock_delay.assert_called()
