# Generated by Django 5.1.15 on 2026-02-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Note",
        ),
    ]
