# Generated by Django 6.0.6 on 2026-07-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_about_customuser_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="linkedin_connected",
            field=models.BooleanField(default=False),
        ),
    ]
