# Generated by Django 6.0.6 on 2026-07-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_linkedin_connected"),
        ("blog", "0005_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="saved_blogs",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by", to="blog.blog"
            ),
        ),
    ]
