# Generated by Django 6.0.6 on 2026-07-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_saved_blogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auto_post_to_linkedin",
            field=models.BooleanField(default=False),
        ),
    ]
